<section class="container-lg text-center col-11 col-sm-11 col-md-9 col-lg-8 col-xl-7 mb-5 preguntas-frecuentes" style="margin-top: 130px;">
    <h2 class="fw-bolder fs-1 pt-4 my-4 my-lg-5">Terminos y Condiciones</h2>
    <div class="text-start preguntas-frecuentes">
        <h3 class="mb-4 fs-3 fw-bold" style="font-weight: 600;">CONOCIMIENTO Y ACEPTACIÓN DE LAS CONDICIONES DE USO:</h3>
        <p style="line-height: 24px; ">El servicio que Juanchos LAB brinda al usuario (en adelante "Usuario") en virtud de los términos y condiciones del presente Acuerdo de Términos y Condiciones del servicio y de conformidad con las normas de operación y disposiciones publicadas periódicamente por Juanchos LAB. El presente documento supone el acuerdo completo entre el Usuario y el Titular y prevalece sobre cualquier acuerdo anterior suscrito por las partes en relación con el objeto del presente. El presente aviso e información legales regula el uso del servicio y que el Titular pone a disposición de los usuarios de Internet.</p>
        <h3 class="mb-4 fs-3 fw-bold" style="font-weight: 600;">DESCRIPCIÓN DEL SERVICIO.</h3>
        <p style="line-height: 24px; ">Los servicios prestados por Juanchos LAB son de venta de productos a distancia a través de Internet. El Titular pone a disposición del Usuario el servicio web de carácter gratuito para la información y escaparate virtual de los productos. Los precios de los productos están fijados en cada artículo y son visibles antes de la adquisición del producto desde nuestro servicio. Los precios reflejados en la página son los precios definitivos salvo error tipográfico. Los productos en oferta o con descuento aparecen marcados como tal, indicándose el correspondiente descuento aplicado. Todos los precios están expresados en pesos. El Titular se reserva el derecho de modificar el precio de cualquier producto sin previo aviso. El Titular podrá, en un futuro, proporcionar al Usuario nuevos contenidos, servicios, productos o facilidades adicionales, sean o no gratuitas, que incrementen las prestaciones disponibles para el Usuario. A su vez, el Titular se reserva el derecho de cancelar unilateralmente cualquiera de los contenidos, servicios o utilidades incorporadas al servicio Juanchos LAB.</p>
        <h3 class="mb-4 fs-3 fw-bold" style="font-weight: 600;">MODIFICACIONES EN LAS CONDICIONES DEL SERVICIO.</h3>
        <p style="line-height: 24px; ">El Usuario acepta que el Titular podrá, cuando lo considere conveniente, realizar correcciones, mejoras o modificaciones en la Información o los Servicios, sin que ello de lugar, ni derecho a ninguna reclamación o indemnización, ni implique reconocimiento de responsabilidad alguna. La utilización ininterrumpida de Juanchos LAB por parte del Usuario constituirá una ratificación del presente documento, con las modificaciones y cambios que se hubieran introducido.</p>
        <h3 class="mb-4 fs-3 fw-bold" style="font-weight: 600;">CONDUCTA DEL USUARIO.</h3>
        <p style="line-height: 24px; ">El Usuario es el único responsable por el contenido de las transmisiones a través del Servicio. La utilización del servicio por parte del Usuario está sometida a las leyes y reglamentos locales, provinciales, nacionales e internacionales. El Usuario acepta: (1) no utilizar el Servicio con fines ilícitos, ni los prohibidos en este documento; (2) no interferir en los sistemas de redes conectados con el Servicio ni desarticularlos; (3) atenerse a todos los reglamentos, disposiciones y procedimientos de los sistemas de redes conectados con el Servicio. El Usuario no obstaculizará el uso del Servicio de otro Usuario ni el uso de servicios similares por parte de otra entidad. El titular podrá, según su propio criterio, dar por terminado el servicio retrospectivo, es en forma inmediata, si la conducta del usuario no fuera acorde con estos términos y condiciones.</p>
        <h3 class="mb-4 fs-3 fw-bold" style="font-weight: 600;">TÉRMINOS GENERALES.</h3>
        <p style="line-height: 24px; ">El presente acuerdo se regirá por la Ley argentina, sometiéndose las partes para cualquier cuestión litigiosa derivada del presente acuerdo a los Juzgados y Tribunales de la Ciudad Autónoma de Buenos Aires, Argentina. El Usuario no cederá derecho ni obligación alguna derivada del presente acuerdo, salvo que medie el consentimiento expreso por escrito del Titular. Cualquier intento de cesión del Acuerdo sin el mencionado consentimiento será nulo y carecerá de todo efecto. No obstante lo anterior, el Titular tendrá derecho a ceder el presente acuerdo con todos sus derechos y obligaciones ya sea por venta del servicio, disolución, escisión, fusión de empresas o de cualquier otra forma de transmisión. Este contrato será de aplicación obligatoria y tendrá efecto entre las partes y sus respectivos representantes, herederos, administradores, sucesores y titulares de transmisiones autorizadas, salvo lo aquí establecido. Si un tribunal competente considerara que alguna disposición o disposiciones del presente acuerdo fuese contraria a la ley, tal o tales disposiciones serán redactadas nuevamente de forma tal que reflejen lo más fielmente posible las intenciones de las partes, mientras las otras disposiciones se mantendrán vigentes y aplicables. En el supuesto de que alguna de las cláusulas del presente Acuerdo resultara inválida o inaplicable, la parte válida o aplicable y las restantes disposiciones del Acuerdo se mantendrán vigentes y aplicables. Toda renuncia al derecho de reclamación (explícita o implícita) de cualquiera de las partes a cualquier infracción del presente Acuerdo no constituirá renuncia al derecho a reclamación por otra infracción o por una infracción subsiguiente. No se renunciará a ninguna disposición del Acuerdo por acto, omisión o desconocimiento de una de las partes o de sus representantes o empleados, sino por medio de un instrumento escrito y firmado en el cual se renuncie expresamente a dicha disposición. Los títulos de las cláusulas en el presente acuerdo se utilizan únicamente para la comodidad de las partes y carecen de significación legal o contractual.</p>
</section>